site_name: test-project
site_description: A new test project!
repo_url: https://github.com/gauriwankhade/test-project-web
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/gauriwankhade">gauriwankhade</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
