# Generated by Django 3.1.4 on 2021-01-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='downloaded_url',
            field=models.URLField(default=None, max_length=255, null=True),
        ),
    ]
