# Generated by Django 3.1.4 on 2021-01-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210103_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='downloaded_url',
            field=models.URLField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
