# Generated by Django 3.1.4 on 2021-01-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210103_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='downloaded_url',
        ),
        migrations.AddField(
            model_name='book',
            name='downloaded_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
